# Generated by Django 5.2.4 on 2025-08-27 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizeduser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customizeduser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
